"""Helpers for emitting deployable artefacts from a fitted estimator."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

import numpy as np


HEADER_TEMPLATE = """// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler {path}
#pragma once

#include <cstddef>

namespace chroma_predictor {{

static constexpr int FEATURE_COUNT = {fc};
static constexpr const char* MODEL_CLASS = "{model_class}";

// Feature ordering: {feature_order}
static const double SCALER_MEAN[FEATURE_COUNT] = {{
{mean_lines}
}};
static const double SCALER_STD[FEATURE_COUNT] = {{
{std_lines}
}};

}}  // namespace chroma_predictor
"""


def _fmt_array(arr: np.ndarray) -> str:
    """Indented one-per-line C double literals with trailing comma."""
    lines = []
    for x in arr:
        # Format with high precision; ensure decimal point for floats
        formatted = f"{float(x):.17g}"
        # If no decimal or exponent, add .0
        if '.' not in formatted and 'e' not in formatted.lower():
            formatted += ".0"
        lines.append(f"    {formatted},")
    return "\n".join(lines)


def write_scaler_header(scaler, model_class: str,
                         feature_names: Sequence[str], path) -> None:
    """Emit scaler.h containing the inline mean/std arrays for a fitted
    sklearn StandardScaler. `model_class` is recorded for runtime checks
    (linear vs tree models pick raw vs scaled inputs)."""
    mean = np.asarray(scaler.mean_, dtype=float)
    std  = np.asarray(scaler.scale_, dtype=float)   # .scale_ ≡ √var_
    if mean.size != len(feature_names):
        raise ValueError(f"scaler has {mean.size} features, "
                         f"feature_names has {len(feature_names)}")

    text = HEADER_TEMPLATE.format(
        path=Path(path).name,
        fc=mean.size,
        model_class=model_class,
        feature_order=", ".join(feature_names),
        mean_lines=_fmt_array(mean),
        std_lines=_fmt_array(std),
    )
    Path(path).write_text(text)


def emit_model_meta(meta: dict, path) -> None:
    """Pretty-print provenance JSON next to model.cpp / scaler.h."""
    Path(path).write_text(json.dumps(meta, indent=2, sort_keys=True))
