// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler_v1.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 2;
static constexpr const char* MODEL_CLASS = "linear";

// Feature ordering: V, E
static const double SCALER_MEAN[FEATURE_COUNT] = {
    1061454.3442982456,
    10769045.649122806,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    3099478.1935036047,
    31842790.483842406,
};

// Deployment-time rounding policy (set by trainer to operate at a chosen
// VR/θ̂ tradeoff point; see model/model_meta.json:rounding_policy).
//   USE_FLOOR=true  → fuzzy_number = (int)floor(score(input) + SCORE_SHIFT)
//   USE_FLOOR=false → fuzzy_number = (int)round(score(input) + SCORE_SHIFT)
static constexpr bool   USE_FLOOR   = false;
static constexpr double SCORE_SHIFT = 0;

}  // namespace chroma_predictor
