// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler_xgb.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "xgb";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    4819770.5789473681,
    24574517.684210528,
    22.67940196048453,
    50.879949771125439,
    2031.8396123422986,
    0.55006842587439397,
    0.9186333566012963,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    11578265.202042807,
    34704204.008313425,
    25.093052498552794,
    42.339777856003032,
    5751.3631944552553,
    0.24041919778770957,
    0.058620752385791688,
};

}  // namespace chroma_predictor
