// Auto-generated by scratchpad/emit_skew.py — DO NOT EDIT BY HAND.
// 4-feature skew predictor: V, E, d, gamma1 (moment degree skewness).
// rf is trained on RAW features — no standardisation at deployment.
#pragma once

namespace chroma_predictor_skew {

static constexpr int FEATURE_COUNT = 4;
static constexpr const char* MODEL_CLASS = "rf";

// Same rounding policy as the v3 deployment (floor + shift).
static constexpr bool   USE_FLOOR   = true;
static constexpr double SCORE_SHIFT = -0.5;

}  // namespace chroma_predictor_skew
