// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler_gbr.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "gbr";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    1118494.5813953488,
    6621986.1279069772,
    12.363224220938459,
    36.218321548663923,
    558.53517195211066,
    0.42352807720711794,
    0.9416606298429967,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    2447039.0227507297,
    10125231.537744319,
    15.996222036530845,
    78.091898415339088,
    2813.4730479544464,
    0.26786212467947196,
    0.061160182653990723,
};

}  // namespace chroma_predictor
