// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler_rf.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "rf";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    1514022.8476190476,
    8458936.8857142851,
    10.977285471578604,
    29.06946332037715,
    507.35964286628968,
    0.35124078089416255,
    0.95720297591055381,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    3798643.2915232582,
    17262384.903774723,
    15.277904189904362,
    72.395178442592112,
    2674.9024345157668,
    0.2478503645376994,
    0.05573329069724578,
};

}  // namespace chroma_predictor
