// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "rf";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    1521266.7894736843,
    8499408.6411483251,
    10.988095695280181,
    29.179157560444281,
    509.77073600693888,
    0.35140223807901044,
    0.9572406283542183,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    3806272.8164996598,
    17293691.031403378,
    15.313609330977499,
    72.55075340218059,
    2681.0664238690047,
    0.24843158280720593,
    0.055863800202445663,
};

// Deployment-time rounding policy (set by trainer to operate at a chosen
// VR/θ̂ tradeoff point; see model/model_meta.json:rounding_policy).
//   USE_FLOOR=true  → fuzzy_number = (int)floor(score(input) + SCORE_SHIFT)
//   USE_FLOOR=false → fuzzy_number = (int)round(score(input) + SCORE_SHIFT)
static constexpr bool   USE_FLOOR   = true;
static constexpr double SCORE_SHIFT = -0.5;

}  // namespace chroma_predictor
