// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "linear";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    6393331.923076923,
    26361580.923076924,
    25.124853838808413,
    48.925960872727089,
    892.75215758886043,
    0.48110046445520116,
    0.93078549145402711,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    13674963.616547743,
    38156109.762450859,
    29.267364559216858,
    48.489043321393652,
    1654.9061547791428,
    0.26024298702990079,
    0.056728981576481076,
};

}  // namespace chroma_predictor
