// Auto-generated by scratchpad/emit_3feat.py — DO NOT EDIT BY HAND.
// 3-feature predictor: V, E, d (= E/V). All available from the graph
// header — feature extraction costs nothing.
// rf is trained on RAW features — no standardisation at deployment.
#pragma once

namespace chroma_predictor_3feat {

static constexpr int FEATURE_COUNT = 3;
static constexpr const char* MODEL_CLASS = "rf";

// Same rounding policy as the v3 deployment (floor + shift).
static constexpr bool   USE_FLOOR   = true;
static constexpr double SCORE_SHIFT = -0.5;

}  // namespace chroma_predictor_3feat
