// Auto-generated by model/emit.py — DO NOT EDIT BY HAND.
// Regenerate via:  python3 -m model.train ... --emit-scaler scaler.h
#pragma once

#include <cstddef>

namespace chroma_predictor {

static constexpr int FEATURE_COUNT = 7;
static constexpr const char* MODEL_CLASS = "rf";

// Feature ordering: V, E, d, s, R, GI, H_er
static const double SCALER_MEAN[FEATURE_COUNT] = {
    1472751.3989898991,
    8070088.777777778,
    10.989796044013369,
    27.347927741771965,
    348.2839397881695,
    0.33417636141832119,
    0.9612911288286401,
};
static const double SCALER_STD[FEATURE_COUNT] = {
    3744644.1999953287,
    16337810.381555768,
    15.683697417967741,
    73.195975207499231,
    2044.0450789401889,
    0.23994789856982413,
    0.053147942737777489,
};

// Deployment-time rounding policy (set by trainer to operate at a chosen
// VR/θ̂ tradeoff point; see model/model_meta.json:rounding_policy).
//   USE_FLOOR=true  → fuzzy_number = (int)floor(score(input) + SCORE_SHIFT)
//   USE_FLOOR=false → fuzzy_number = (int)round(score(input) + SCORE_SHIFT)
static constexpr bool   USE_FLOOR   = true;
static constexpr double SCORE_SHIFT = -0.5;

}  // namespace chroma_predictor
